//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;

    public partial class TableEmp
    {
        public int Id { get; set; }
        public string NameEmp { get; set; }
        public string Age { get; set; }
        public string Salary { get; set; }
        public string EmpDep { get; set; }


        public override string ToString() => $"{Id,5} {NameEmp,15} {Age,5} {Salary,7} {EmpDep,10}";
    }
}
